// <auto-generated />
using KarlaR_300997958.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KarlaR_300997958.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KarlaR_300997958.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseDesc")
                        .IsRequired();

                    b.Property<string>("CourseFaculty");

                    b.Property<string>("CourseName")
                        .IsRequired();

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("KarlaR_300997958.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FacultyCourse");

                    b.Property<string>("FacultyEMail")
                        .IsRequired();

                    b.Property<string>("FacultyName")
                        .IsRequired();

                    b.Property<string>("FacultySurname")
                        .IsRequired();

                    b.HasKey("FacultyCode");

                    b.ToTable("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
